### ISSUE TITLE
CVPR 2020

### ISSUE THREAD

**Issue by RudyChin** [MingSun-Tse/EfficientDNNs#4]
Hi,

Thank you for maintaining this convenient repo! It helps me survey papers more efficiently in the field of model compression.
I recently have a paper regarding filter pruning accepted at CVPR 2020 as oral presentation: https://arxiv.org/abs/1904.12368. It would be great if you can add this to the repo, too.

Thanks,
Rudy

**Comment by MingSun-Tse** [comment]
> Hi,
> 
> Thank you for maintaining this convenient repo! It helps me survey papers more efficiently in the field of model compression.
> I recently have a paper regarding filter pruning accepted at CVPR 2020 as oral presentation: https://arxiv.org/abs/1904.12368. It would be great if you can add this to the repo, too.
> 
> Thanks,
> Rudy

Hi Rudy,

Congrats on your CVPR paper! I have included your work. Thanks for your attention to this repo.

Best,
